# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.
name: Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  schedule:
    - cron: '53 0 * * *' # Daily at 00:53 UTC
  # Triggered on push to branch "main" by .github/workflows/release.yaml
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install tox
        run: python3 -m pip install tox
      - name: Run linters
        run: tox run -e lint

  unit-test:
    name: Unit tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install tox
        run: python -m pip install tox
      - name: Run tests
        run: tox run -e unit

  build:
    name: Build charms
    uses: canonical/data-platform-workflows/.github/workflows/build_charms_with_cache.yaml@v7

  integration-test:
    strategy:
      fail-fast: false
      matrix:
        tox-environments:
          - integration-charm
          - integration-password
          - integration-redis-relation
          - integration-scaling
    name: ${{ matrix.tox-environments }}
    needs:
      - lint
      - unit-test
      - build
    runs-on: ubuntu-22.04
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup operator environment
        # TODO: Replace with custom image on self-hosted runner
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: microk8s
          channel: "1.28-strict/stable"
          juju-channel: 2.9/stable
          bootstrap-options: "--agent-version 2.9.43"
      - name: Download packed charm(s)
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.build.outputs.artifact-name }}
      - name: Select tests
        id: select-tests
        run: |
          if [ "${{ github.event_name }}" == "schedule" ]
          then
            echo Running unstable and stable tests
            echo "mark_expression=" >> $GITHUB_OUTPUT
          else
            echo Skipping unstable tests
            echo "mark_expression=not unstable" >> $GITHUB_OUTPUT
          fi
      - name: Run integration tests
        run: tox run -e ${{ matrix.tox-environments }} -- -m '${{ steps.select-tests.outputs.mark_expression }}'
        env:
          CI_PACKED_CHARMS: ${{ needs.build.outputs.charms }}

  integration-test-relation-single-unit:
    name: Integration tests (relation, num_units=1)
    needs:
      - lint
      - unit-test
      - build
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup operator environment
        # TODO: Replace with custom image on self-hosted runner
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: microk8s
          channel: "1.28-strict/stable"
          juju-channel: 2.9/stable
          bootstrap-options: "--agent-version 2.9.43"
      - name: Download packed charm(s)
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.build.outputs.artifact-name }}
      - name: Run integration tests
        run: tox run -e integration-relation -- --num-units 1 -m '${{ steps.select-tests.outputs.mark_expression }}'
        env:
          CI_PACKED_CHARMS: ${{ needs.build.outputs.charms }}


  # integration-test-general:
  #   name: Integration tests (general)
  #   needs:
  #     - lint
  #     - unit-test
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Setup operator environment
  #       uses: charmed-kubernetes/actions-operator@main
  #       with:
  #         provider: microk8s
  #         bootstrap-options: "--agent-version 2.9.43"
  #     - name: Run integration tests
  #       run: tox -e integration-charm

  # integration-test-relation:
  #   name: Integration tests (relation)
  #   needs:
  #     - lint
  #     - unit-test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Setup operator environment
  #       uses: charmed-kubernetes/actions-operator@main
  #       with:
  #         provider: microk8s
  #         bootstrap-options: "--agent-version 2.9.43"
  #     - name: Run integration tests
  #       run: tox -e integration-relation

  # integration-test-relation-single-unit:
  #   name: Integration tests (relation, num_units=1)
  #   needs:
  #     - lint
  #     - unit-test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Setup operator environment
  #       uses: charmed-kubernetes/actions-operator@main
  #       with:
  #         provider: microk8s
  #         bootstrap-options: "--agent-version 2.9.43"
  #     - name: Run integration tests
  #       run: tox -e integration-relation -- --num-units 1

  # integration-test-password:
  #   name: Integration tests (password)
  #   needs:
  #     - lint
  #     - unit-test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Setup operator environment
  #       uses: charmed-kubernetes/actions-operator@main
  #       with:
  #         provider: microk8s
  #         bootstrap-options: "--agent-version 2.9.43"
  #     - name: Run integration tests
  #       run: tox -e integration-password

  # integration-test-scaling:
  #   name: Integration tests (scaling)
  #   needs:
  #     - lint
  #     - unit-test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Setup operator environment
  #       uses: charmed-kubernetes/actions-operator@main
  #       with:
  #         provider: microk8s
  #         bootstrap-options: "--agent-version 2.9.29"
  #     - name: Run integration tests
  #       run: tox -e integration-scaling